import { spawn } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import type { AppMcpStorage } from '../../core/providers/types';
import type { ManagedMcpServer, McpServerConfig, QmdKnowledgeBaseSettings } from '../../core/types';
import type { ClaudianSettings } from '../../core/types/settings';
import { getEnhancedPath } from '../../utils/env';
import { expandHomePath, normalizePathForFilesystem } from '../../utils/path';

const DEFAULT_INDEX_NAME = 'index';
const QMD_SERVER_NAME = 'qmd';
const OUTPUT_LIMIT = 120_000;
const GENERATED_CONFIG_HEADER = '# Generated by Claudian QMD knowledge base settings.';

export interface QmdResolvedPaths {
  storeDir: string;
  configDir: string;
  configPath: string;
  indexPath: string;
  defaultCacheDir: string;
  defaultConfigDir: string;
  defaultIndexPath: string;
  defaultConfigPath: string;
  defaultModelDir: string;
}

export interface QmdPrepareResult {
  configPath: string;
  indexPath: string;
  linkMessages: string[];
}

export interface QmdCommandResult {
  command: string;
  args: string[];
  exitCode: number | null;
  stdout: string;
  stderr: string;
  timedOut: boolean;
}

function getHomeDir(): string {
  return process.env.HOME || process.env.USERPROFILE || os.homedir();
}

function getDefaultCacheDir(): string {
  const root = process.env.XDG_CACHE_HOME || path.join(getHomeDir(), '.cache');
  return path.join(root, 'qmd');
}

function getDefaultConfigDir(): string {
  const root = process.env.XDG_CONFIG_HOME || path.join(getHomeDir(), '.config');
  return path.join(root, 'qmd');
}

function normalizeIndexName(value: string | undefined): string {
  const trimmed = value?.trim() || DEFAULT_INDEX_NAME;
  return trimmed.replace(/[\\/]/g, '_') || DEFAULT_INDEX_NAME;
}

function resolveUserPath(value: string | undefined, fallback: string): string {
  const raw = value?.trim() || fallback;
  return normalizePathForFilesystem(expandHomePath(raw));
}

function resolveVaultPath(value: string | undefined, vaultPath: string, fallback: string): string {
  const raw = value?.trim() || fallback;
  const expanded = normalizePathForFilesystem(expandHomePath(raw));
  return path.isAbsolute(expanded) ? expanded : path.join(vaultPath, expanded);
}

function splitLines(value: string | undefined): string[] {
  return (value ?? '')
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(Boolean);
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function createQmdConfigYaml(settings: QmdKnowledgeBaseSettings, vaultPath: string): string {
  const collectionName = settings.collectionName.trim() || 'vault';
  const pattern = settings.collectionPattern.trim() || '**/*.md';
  const ignore = splitLines(settings.collectionIgnore);
  const lines: string[] = [GENERATED_CONFIG_HEADER];

  if (settings.globalContext.trim()) {
    lines.push(`global_context: ${yamlString(settings.globalContext.trim())}`);
  }

  lines.push('collections:');
  lines.push(`  ${yamlString(collectionName)}:`);
  lines.push(`    path: ${yamlString(vaultPath)}`);
  lines.push(`    pattern: ${yamlString(pattern)}`);

  if (ignore.length > 0) {
    lines.push('    ignore:');
    for (const entry of ignore) {
      lines.push(`      - ${yamlString(entry)}`);
    }
  }

  if (settings.collectionContext.trim()) {
    lines.push('    context:');
    lines.push(`      "/": ${yamlString(settings.collectionContext.trim())}`);
  }

  const localEmbedModel = settings.localEmbedModel.trim();
  if (settings.embeddingBackend === 'local' && localEmbedModel) {
    lines.push('models:');
    lines.push(`  embed: ${yamlString(localEmbedModel)}`);
  }

  return `${lines.join('\n')}\n`;
}

function envValue(value: string): string {
  if (!/[#\s'"]/.test(value)) {
    return value;
  }
  return `"${value.replace(/"/g, '\\"')}"`;
}

function isSameSymlink(linkPath: string, targetPath: string): boolean {
  try {
    const linkTarget = fs.readlinkSync(linkPath);
    const resolvedLinkTarget = path.resolve(path.dirname(linkPath), linkTarget);
    return path.normalize(resolvedLinkTarget) === path.normalize(targetPath);
  } catch {
    return false;
  }
}

function ensureParentDir(filePath: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function ensureFileLink(linkPath: string, targetPath: string): string {
  ensureParentDir(linkPath);
  ensureParentDir(targetPath);

  try {
    const linkStat = fs.lstatSync(linkPath);
    if (linkStat.isSymbolicLink()) {
      if (isSameSymlink(linkPath, targetPath)) {
        return `Link already exists: ${linkPath}`;
      }
      return `Skipped existing symlink with different target: ${linkPath}`;
    }

    if (!fs.existsSync(targetPath)) {
      fs.renameSync(linkPath, targetPath);
    } else {
      return `Skipped existing file: ${linkPath}`;
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      return `Skipped inaccessible path: ${linkPath}`;
    }
  }

  if (!fs.existsSync(targetPath)) {
    fs.closeSync(fs.openSync(targetPath, 'a'));
  }

  try {
    fs.symlinkSync(targetPath, linkPath, 'file');
    return `Linked ${linkPath} -> ${targetPath}`;
  } catch (error) {
    return `Failed to link ${linkPath}: ${error instanceof Error ? error.message : String(error)}`;
  }
}

function moveFileIfTargetMissing(sourcePath: string, targetPath: string): string | null {
  try {
    const sourceStat = fs.lstatSync(sourcePath);
    if (!sourceStat.isFile()) {
      return null;
    }

    if (fs.existsSync(targetPath)) {
      return null;
    }

    ensureParentDir(targetPath);
    fs.renameSync(sourcePath, targetPath);
    return `Moved ${sourcePath} -> ${targetPath}`;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }

    return `Failed to move ${sourcePath}: ${error instanceof Error ? error.message : String(error)}`;
  }
}

function writeGeneratedConfigIfSafe(configPath: string, content: string): string | null {
  try {
    const existing = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf-8') : null;
    if (existing && !existing.startsWith(GENERATED_CONFIG_HEADER)) {
      return `Kept existing QMD config: ${configPath}`;
    }

    fs.writeFileSync(configPath, content, 'utf-8');
    return existing ? `Updated generated QMD config: ${configPath}` : `Created QMD config: ${configPath}`;
  } catch (error) {
    return `Failed to write QMD config: ${error instanceof Error ? error.message : String(error)}`;
  }
}

function resolveLegacyDir(value: string, vaultPath: string, fallbackName: string): string | null {
  const trimmed = value.trim();
  if (trimmed) {
    return resolveUserPath(trimmed, trimmed);
  }

  const detected = path.join(vaultPath, fallbackName);
  return fs.existsSync(detected) ? detected : null;
}

function moveLegacyModels(legacyCacheDir: string, defaultModelDir: string): string | null {
  const legacyModelDir = path.join(legacyCacheDir, 'models');
  if (!fs.existsSync(legacyModelDir)) {
    return null;
  }

  if (fs.existsSync(defaultModelDir)) {
    return `Skipped legacy models because target exists: ${defaultModelDir}`;
  }

  try {
    fs.mkdirSync(path.dirname(defaultModelDir), { recursive: true });
    fs.renameSync(legacyModelDir, defaultModelDir);
    return `Moved legacy models to ${defaultModelDir}`;
  } catch (error) {
    return `Failed to move legacy models: ${error instanceof Error ? error.message : String(error)}`;
  }
}

export function getQmdSettings(settings: ClaudianSettings): QmdKnowledgeBaseSettings {
  return settings.qmdKnowledgeBase;
}

function maybeGetQmdSettings(settings: ClaudianSettings): QmdKnowledgeBaseSettings | null {
  return (settings as { qmdKnowledgeBase?: QmdKnowledgeBaseSettings | null }).qmdKnowledgeBase ?? null;
}

export function resolveQmdPaths(settings: QmdKnowledgeBaseSettings, vaultPath: string): QmdResolvedPaths {
  const indexName = normalizeIndexName(settings.indexName);
  const storeDir = resolveVaultPath(settings.storeDir, vaultPath, 'QMD');
  const configDir = path.join(storeDir, 'config');
  const defaultCacheDir = resolveUserPath(settings.defaultCacheDir, getDefaultCacheDir());
  const defaultConfigDir = resolveUserPath(settings.defaultConfigDir, getDefaultConfigDir());

  return {
    storeDir,
    configDir,
    configPath: path.join(configDir, `${indexName}.yml`),
    indexPath: path.join(storeDir, `${indexName}.sqlite`),
    defaultCacheDir,
    defaultConfigDir,
    defaultIndexPath: path.join(defaultCacheDir, `${indexName}.sqlite`),
    defaultConfigPath: path.join(defaultConfigDir, `${indexName}.yml`),
    defaultModelDir: path.join(defaultCacheDir, 'models'),
  };
}

export function buildQmdEnvironmentVariables(
  settings: QmdKnowledgeBaseSettings,
  vaultPath: string | null,
): Record<string, string> {
  if (!settings.enabled || !vaultPath) {
    return {};
  }

  const paths = resolveQmdPaths(settings, vaultPath);
  const env: Record<string, string> = {
    INDEX_PATH: paths.indexPath,
    QMD_CONFIG_DIR: paths.configDir,
    QMD_KNOWLEDGE_BASE_DIR: paths.storeDir,
    QMD_COLLECTION_NAME: settings.collectionName.trim() || 'vault',
    NO_COLOR: '1',
  };

  if (settings.embeddingBackend === 'local') {
    const localEmbedModel = settings.localEmbedModel.trim();
    if (localEmbedModel) {
      env.QMD_EMBED_MODEL = localEmbedModel;
    }
    return env;
  }

  env.QMD_EMBED_PROVIDER = settings.apiProvider.trim() || 'openai';

  const apiBaseUrl = settings.apiBaseUrl.trim();
  if (apiBaseUrl) {
    env.QMD_EMBED_API_URL = apiBaseUrl;
    env.QMD_EMBED_BASE_URL = apiBaseUrl;
  }

  const apiModel = settings.apiModel.trim();
  if (apiModel) {
    env.QMD_EMBED_MODEL = apiModel;
  }

  const apiDimensions = settings.apiDimensions.trim();
  if (apiDimensions) {
    env.QMD_EMBED_DIMENSIONS = apiDimensions;
  }

  const apiKey = settings.apiKey.trim();
  if (apiKey) {
    env.QMD_EMBED_API_KEY = apiKey;
    const apiKeyEnvVar = settings.apiKeyEnvVar.trim();
    if (apiKeyEnvVar) {
      env[apiKeyEnvVar] = apiKey;
    }
  }

  return env;
}

export function buildQmdEnvironmentText(settings: ClaudianSettings, vaultPath: string | null): string {
  const qmdSettings = maybeGetQmdSettings(settings);
  if (!qmdSettings) {
    return '';
  }

  const env = buildQmdEnvironmentVariables(qmdSettings, vaultPath);
  const entries = Object.entries(env);
  if (entries.length === 0) {
    return '';
  }

  return [
    '# Generated by Claudian QMD knowledge base settings.',
    ...entries.map(([key, value]) => `${key}=${envValue(value)}`),
  ].join('\n');
}

export function buildQmdAgentInstructions(settings: ClaudianSettings, vaultPath: string | null): string {
  const qmdSettings = maybeGetQmdSettings(settings);
  if (!qmdSettings?.enabled || !vaultPath) {
    return '';
  }

  const paths = resolveQmdPaths(qmdSettings, vaultPath);
  const collectionName = qmdSettings.collectionName.trim() || 'vault';

  return `## QMD Knowledge Base

This vault is configured as a QMD knowledge base.

- Runtime environment already points QMD at this vault: \`INDEX_PATH=${paths.indexPath}\` and \`QMD_CONFIG_DIR=${paths.configDir}\`.
- Prefer \`qmd query --json "<question>"\`, \`qmd search --json "<terms>"\`, and \`qmd get <path-or-docid>\` for broad vault retrieval before manual file-by-file search.
- Use collection \`${collectionName}\` when narrowing searches, for example \`qmd query -c ${collectionName} --json "<question>"\`.
- The llmwiki skills and rag-skill can use this QMD setup through the generated environment variables.
- Do not run \`qmd collection add\`, \`qmd update\`, \`qmd embed\`, or \`qmd cleanup\` unless the user asks for indexing or maintenance.`;
}

export function buildQmdMcpServer(
  settings: QmdKnowledgeBaseSettings,
  vaultPath: string,
): ManagedMcpServer {
  const description = 'QMD search over this Obsidian vault knowledge base';
  const config: McpServerConfig = settings.mcpTransport === 'http'
    ? {
      type: 'http',
      url: settings.mcpHttpUrl.trim() || 'http://localhost:8181/mcp',
    }
    : {
      type: 'stdio',
      command: settings.qmdCommand.trim() || 'qmd',
      args: ['mcp'],
      env: buildQmdEnvironmentVariables(settings, vaultPath),
    };

  return {
    name: QMD_SERVER_NAME,
    config,
    enabled: true,
    contextSaving: true,
    description,
  };
}

export async function upsertQmdMcpServer(
  mcpStorage: AppMcpStorage,
  settings: QmdKnowledgeBaseSettings,
  vaultPath: string,
): Promise<void> {
  const servers = await mcpStorage.load();
  const nextServer = buildQmdMcpServer(settings, vaultPath);
  const existingIndex = servers.findIndex(server => server.name === QMD_SERVER_NAME);

  if (existingIndex >= 0) {
    servers[existingIndex] = {
      ...servers[existingIndex],
      ...nextServer,
    };
  } else {
    servers.push(nextServer);
  }

  await mcpStorage.save(servers);
}

export class QmdKnowledgeBaseService {
  constructor(
    private readonly settings: QmdKnowledgeBaseSettings,
    private readonly vaultPath: string | null,
  ) {}

  prepareStorage(): QmdPrepareResult {
    if (!this.vaultPath) {
      throw new Error('QMD requires a local Obsidian vault path.');
    }

    const paths = resolveQmdPaths(this.settings, this.vaultPath);
    fs.mkdirSync(paths.storeDir, { recursive: true });
    fs.mkdirSync(paths.configDir, { recursive: true });

    const linkMessages: string[] = [];

    if (this.settings.createDefaultLinks) {
      const movedDefaultConfig = moveFileIfTargetMissing(paths.defaultConfigPath, paths.configPath);
      if (movedDefaultConfig) {
        linkMessages.push(movedDefaultConfig);
      }
    }

    const legacyCacheDir = resolveLegacyDir(this.settings.legacyCacheDir, this.vaultPath, '_qmd-cache');
    if (legacyCacheDir) {
      const movedModels = moveLegacyModels(legacyCacheDir, paths.defaultModelDir);
      if (movedModels) {
        linkMessages.push(movedModels);
      }
    }

    const legacyConfigDir = resolveLegacyDir(this.settings.legacyConfigDir, this.vaultPath, '_qmd-config');
    if (legacyConfigDir) {
      const movedLegacyConfig = moveFileIfTargetMissing(path.join(legacyConfigDir, `${normalizeIndexName(this.settings.indexName)}.yml`), paths.configPath);
      if (movedLegacyConfig) {
        linkMessages.push(movedLegacyConfig);
      }
    }

    const configMessage = writeGeneratedConfigIfSafe(paths.configPath, createQmdConfigYaml(this.settings, this.vaultPath));
    if (configMessage) {
      linkMessages.push(configMessage);
    }

    if (this.settings.createDefaultLinks) {
      linkMessages.push(ensureFileLink(paths.defaultIndexPath, paths.indexPath));
      linkMessages.push(ensureFileLink(paths.defaultConfigPath, paths.configPath));
    }

    if (legacyCacheDir) {
      linkMessages.push(ensureFileLink(path.join(legacyCacheDir, `${normalizeIndexName(this.settings.indexName)}.sqlite`), paths.indexPath));
    }

    if (legacyConfigDir) {
      linkMessages.push(ensureFileLink(path.join(legacyConfigDir, `${normalizeIndexName(this.settings.indexName)}.yml`), paths.configPath));
    }

    return {
      configPath: paths.configPath,
      indexPath: paths.indexPath,
      linkMessages,
    };
  }

  run(args: string[], options: { timeoutMs?: number } = {}): Promise<QmdCommandResult> {
    if (!this.vaultPath) {
      return Promise.reject(new Error('QMD requires a local Obsidian vault path.'));
    }

    const command = this.settings.qmdCommand.trim() || 'qmd';
    const qmdEnv = buildQmdEnvironmentVariables(this.settings, this.vaultPath);
    const env = {
      ...process.env,
      ...qmdEnv,
      PATH: getEnhancedPath(process.env.PATH),
    } as NodeJS.ProcessEnv;

    return new Promise((resolve, reject) => {
      const child = spawn(command, args, {
        cwd: this.vaultPath ?? process.cwd(),
        env,
        shell: process.platform === 'win32',
      });
      const timeoutMs = options.timeoutMs ?? 5 * 60 * 1000;
      let stdout = '';
      let stderr = '';
      let timedOut = false;

      const append = (current: string, chunk: Buffer): string => {
        const next = current + chunk.toString('utf-8');
        if (next.length <= OUTPUT_LIMIT) {
          return next;
        }
        return next.slice(0, OUTPUT_LIMIT) + '\n[output truncated]';
      };

      const timeout = setTimeout(() => {
        timedOut = true;
        child.kill();
      }, timeoutMs);
      timeout.unref?.();

      child.stdout?.on('data', (chunk: Buffer) => {
        stdout = append(stdout, chunk);
      });
      child.stderr?.on('data', (chunk: Buffer) => {
        stderr = append(stderr, chunk);
      });
      child.on('error', reject);
      child.on('close', (exitCode) => {
        clearTimeout(timeout);
        resolve({
          command,
          args,
          exitCode,
          stdout,
          stderr,
          timedOut,
        });
      });
    });
  }
}
